Fix compiler warning when --enable-embedded is used
ccid.c: In function ‘ccid_error’:
ccid.c:601:21: error: unused parameter ‘log_level’ [-Werror=unused-parameter]
  601 | void ccid_error(int log_level, int error, const char *file, int line,
      |                 ~~~~^~~~~~~~~
ccid.c:601:36: error: unused parameter ‘error’ [-Werror=unused-parameter]
  601 | void ccid_error(int log_level, int error, const char *file, int line,
      |                                ~~~~^~~~~
ccid.c:601:55: error: unused parameter ‘file’ [-Werror=unused-parameter]
  601 | void ccid_error(int log_level, int error, const char *file, int line,
      |                                           ~~~~~~~~~~~~^~~~
ccid.c:601:65: error: unused parameter ‘line’ [-Werror=unused-parameter]
  601 | void ccid_error(int log_level, int error, const char *file, int line,
      |                                                             ~~~~^~~~
ccid.c:602:21: error: unused parameter ‘function’ [-Werror=unused-parameter]
  602 |         const char *function)
      |         ~~~~~~~~~~~~^~~~~~~~