towitoko: do not use "bool" type
Use an explicit "int" in the source code.

Compilation fails on macOS when <os/log.h> is used.

./towitoko/defines.h:52:28: error: cannot combine with previous 'int'
      declaration specifier
typedef int                bool;
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include/stdbool.h:31:14: note:
      expanded from macro 'bool'
             ^
In file included from ifdhandler.c:49:
In file included from ./towitoko/atr.h:26:
./towitoko/defines.h:52:1: warning: typedef requires a name
      [-Wmissing-declarations]
typedef int                bool;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~