macOS does not provide pthread_condattr_setclock()
Fix compilation error:
ccid_usb.c:2105:2: error: call to undeclared function 'pthread_condattr_setclock'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        pthread_condattr_setclock(&condattr, CLOCK_MONOTONIC);
        ^

On macOS, we use CLOCK_MONOTONIC instead (as before).