Add missing unistd.h header
On Mac OS X Mavericks:
parse.c:108:8: warning: implicit declaration of function 'getuid' is invalid in C99 [-Wimplicit-function-declaration]
                        if (getuid())
                            ^
parse.c:233:25: warning: implicit declaration of function 'geteuid' is invalid in C99 [-Wimplicit-function-declaration]
        if ((0 == nb) && (0 != geteuid()))
                               ^
2 warnings generated.


git-svn-id: svn://anonscm.debian.org/svn/pcsclite/trunk/Drivers/ccid@6929 0ce88b0d-b2fd-0310-8134-9614164e65ea