meson: parse depends on pthread
Fix link issue on Ubuntu 20.04

$ ninja
[32/33] Linking target parse.
FAILED: parse
cc  -o parse 'parse@exe/meson-generated_tokenparser.c.o' 'parse@exe/src_parse.c.o' 'parse@exe/src_debug.c.o' 'parse@exe/src_ccid_usb.c.o' 'parse@exe/src_sys_unix.c.o' 'parse@exe/src_strlcpy.c.o' 'parse@exe/src_simclist.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group /usr/lib/x86_64-linux-gnu/libusb-1.0.so /usr/lib/x86_64-linux-gnu/libz.so -Wl,--end-group
/usr/bin/ld: parse@exe/src_ccid_usb.c.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
[33/33] Generating Info.plist with a meson_exe.py custom command.
ninja: build stopped: subcommand failed.

Thanks to Peter Helcmanovsky for the bug report and patch.