Fix compiler warning when --enable-embedded is used
commands.c: In function ‘T0ProcSW1’:
commands.c:2025:28: error: variable ‘sw2’ set but not used [-Werror=unused-but-set-variable]
 2025 |         unsigned char sw1, sw2;
      |                            ^~~
commands.c:2025:23: error: variable ‘sw1’ set but not used [-Werror=unused-but-set-variable]
 2025 |         unsigned char sw1, sw2;
      |                       ^~~